######################################
#                                    #
#   Configuration file for GunGame   #
#                                    #
#       by Dev7ex and DevSnx         #
#                                    #
######################################

config-version: '1.0.0'

# General plugin settings
general:

  # Language of the plugin (location: './locales/en_US.yml')
  # Avaible: en_US , de_DE
  locale: en_US

  prefix: '§8[§aGunGame§8]§r'